version: '3'

services:
  app:
    environment:
      MIX_ENV: test
      DB_NAME: account_repository_test
      DB_USER: ysantos
      DB_PASSWORD: "@dmin123"
      DB_HOST: localhost


  db:
    environment:
      POSTGRES_DB: account_repository_test
      POSTGRES_USER: ysantos
      POSTGRES_PASSWORD: "@dmin123"

