version: '3'

services:
  app:
    environment:
      MIX_ENV: test
      DB_NAME: account_repository_test
      DB_USER: ysantos
      DB_PASSWORD: "@dmin123"
      DB_HOST: db
<<<<<<< HEAD

=======
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
>>>>>>> api/updates

  db:
    environment:
      POSTGRES_DB: account_repository_test
      POSTGRES_USER: ysantos
      POSTGRES_PASSWORD: "@dmin123"

