# Version of docker-compose
version: '3'

services:
  app:
    build:
      context: .
    depends_on:
      - db
<<<<<<< HEAD
=======
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
>>>>>>> api/updates

  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
# Define the volumes
volumes:
  postgres_data:
    driver: local